---
title: "Reference best"
author: "Doris Amoakohene"
date: "`r Sys.Date()`"
output: html_document
---


Reference best test
```{r}
library(atime)
library(ggplot2)
```

overlapping black

```{r}
(subject.size.vec <- unique(as.integer(10^seq(0,3.5,l=100))))
atime.list <- atime::atime(
  setup={
    subject <- paste(rep("a", N), collapse="")
    pattern <- paste(rep(c("a?", "a"), each=N), collapse="")
  },
  PCRE.match=regexpr(pattern, subject, perl=TRUE),
  TRE.match=regexpr(pattern, subject, perl=FALSE),
  constant.replacement=gsub("a","constant size replacement",subject),
  linear.replacement=gsub("a",subject,subject),
  seconds.limit=0.1,
  times=10,
  N=subject.size.vec)
(best.list.R <- atime::references_best(atime.list))
plot(best.list.R)
```



```{r}
png("best.list.R.png", res = 600, width = 15, height = 10, unit = "in")
best.list.R = ggplot() +
  geom_line(aes(x = N, y = median, group = expr.name, colour = expr.name), data = best.list.R$measurements) +
  geom_ribbon(aes(x = N, ymin = min, ymax = max, fill = expr.name), data = best.list.R$measurements, alpha = 0.5) +
  theme(
    plot.title = element_text(size = 30),
    text = element_text(size = 30)
  ) +
  scale_x_log10("N = number of rows", limits = c(NA, 1e4),breaks = c(1, 10, 100, 1000)) +
  scale_y_log10("Computational Time (Seconds)")+
  # scale_fill_manual(values=atime.colors)+
  # scale_color_manual(values=atime.colors)
#directlabels::direct.label(best.list.R, list(cex = 3, "right.polygons")) 
dev.off()
```




```{r}
atime.list[["measurements"]][N==323, .(expr.name, seconds=median, kilobytes)]
pred.list <- predict(best.list, seconds=1e-2, kilobytes=10)
pred.list[["prediction"]]
plot(pred.list)
```


```{r}
png("README-predict.png", width=6, height=4, units="in", res=200)
plot(pred.list)+ggplot2::theme(text=ggplot2::element_text(size=20))
dev.off()
```














```{r}
## When studying asymptotic complexity, always provide sizes on a log
## scale (10^sequence) as below:
(subject.size.vec <- unique(as.integer(10^seq(0,3.5,l=100))))
## Compute asymptotic time and memory measurement:
atime.list.ref <- atime::atime(
  N=subject.size.vec,#vector of sizes.
  setup={#Run for each size, before timings:
    subject <- paste(rep("a", N), collapse="")
    pattern <- paste(rep(c("a?", "a"), each=N), collapse="")
  },
  times=10,#number of timings to compute for each expression.
  seconds.limit=0.1,#max seconds per expression.
  ## Different expressions which will be evaluated for each size N:
  PCRE.match=regexpr(pattern, subject, perl=TRUE),
  TRE.match=regexpr(pattern, subject, perl=FALSE),
  constant.replacement=gsub("a","constant size replacement",subject),
  linear.replacement=gsub("a",subject,subject))

atime.list.ref

plot(atime.list.ref)


# png()
# print(atime.list.ref)
# plot(atime.list.ref)
# ggsave("atime.list.ref.png", atime.list.ref, width = 10, height = 6, units = "in", dpi = 300)
# dev.off()
# 
# atime.list.ref
# plot(atime.list.ref)
```


```{r}
## Compute and plot asymptotic reference lines:
(best.list <- atime::references_best(atime.list.ref))
plot(best.list)

# png()
# print(best.list)
# ggsave("best.list.png", best.list, width = 10, height = 6, units = "in", dpi = 300)
# dev.off()
# 
# best.list
# plot(best.list)
```


```{r}
## Compute and plot data size N for given time/memory.
pred.list <- predict(best.list, seconds=1e-2, kilobytes=10)
plot(pred.list)

# png()
# print(pred.list)
# ggsave("pred.list.png", pred.list, width = 10, height = 6, units = "in", dpi = 300)
# dev.off()
# 
# pred.list
# plot(pred.list)
```


```{r}
subject.size.vec <- unique(as.integer(10^seq(0,3.5,l=100)))
atime.list.ref
plot(atime.list.ref)

png()
print(atime.list.ref)
plot(atime.list.ref)
ggsave("atime.list.ref.png", atime.list.ref, width = 10, height = 6, units = "in", dpi = 300)
dev.off()

atime.list.ref
plot(atime.list.ref)

```



```{r}
best.list.1 <- atime::references_best(atime.list.ref)
plot(best.list.1)

plot(best.list.1)

png()
print(best.list.1)
ggsave("best.list.1.png", best.list.1, width = 10, height = 6, units = "in", dpi = 300)
dev.off()

best.list.1
plot(best.list.1)
```

```{r}
atime.list.ref[["measurements"]][N==323, .(expr.name, seconds=median, kilobytes)]
pred.list.2 <- predict(best.list, seconds=1e-2, kilobytes=10)
pred.list.2[["prediction"]]
plot(pred.list.2)

png()
print(pred.list.2)
ggsave("pred.list.2.png", pred.list.2, width = 10, height = 6, units = "in", dpi = 300)
dev.off()

pred.list.2
plot(pred.list.2)

```

