---
title: "use read for only comparative benchmark section"
author: "Doris Amoakohene"
date: "`r Sys.Date()`"
output: html_document
---



fread: fast CSV reader

```{r}
read.colors <- c(
  "readr::read_csv\n(lazy=TRUE)"="#9970AB",
  "data.table::fread"="#D6604D",
  "utils::read.csv" = "deepskyblue")

n.rows <- 100
seconds.limit <- 1


atime.read.vary.cols <- atime::atime(
  N=as.integer(10^seq(2, 6, by=0.5)),
  setup={
    set.seed(1)
    input.vec <- rnorm(n.rows*N)
    input.mat <- matrix(input.vec, n.rows, N)
    input.df <- data.frame(input.mat)
    input.csv <- tempfile()
    fwrite(input.df, input.csv)
  },
  seconds.limit = seconds.limit,
  "data.table::fread"={
    data.table::fread(input.csv, showProgress = FALSE)
  },
  "readr::read_csv\n(lazy=TRUE)"={
    readr::read_csv(input.csv, progress = FALSE, show_col_types = FALSE, lazy=TRUE)
  },
  "utils::read.csv"=utils::read.csv(input.csv))
```


```{r}
refs.read.vary.cols <- atime::references_best(atime.read.vary.cols)
pred.read.vary.cols <- predict(refs.read.vary.cols)


png("gg.read.3.png", res = 600, width = 15, height = 10, unit = "in")
gg.read.3 <- plot(pred.read.vary.cols)+
  theme(
    text=element_text(size=20),
    axis.text = element_text(size = 16),
    axis.title = element_text(size = 18)
    )+
  scale_x_log10("N = number of columns to read")+
  scale_y_log10("Computation time (seconds)
median line, min/max band
over 10 timings")+
  facet_null()+
  scale_fill_manual(values=read.colors)+
  scale_color_manual(values=read.colors)
directlabels::direct.label(gg.read.3, list(cex = 1.2, "top.polygons"))
dev.off()
```


```{r}

print(gg.read.3)
ggsave("gg.read.3.png", gg.read.3, width = 10, height = 6, units = "in", dpi = 300)
dev.off()

gg.read.3
```

